// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLXppuLIYngz-XqdnDfji-_OB1ZorI4ms',
    appId: '1:227014811374:web:9bc61b5ec272f07d0cddff',
    messagingSenderId: '227014811374',
    projectId: 'ititraining20232',
    authDomain: 'ititraining20232.firebaseapp.com',
    storageBucket: 'ititraining20232.appspot.com',
    measurementId: 'G-GR159QJE9S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDszGkJGxZq64QfrvvR52mLjhlQXY21yqo',
    appId: '1:227014811374:android:f7552e00ab7d41b70cddff',
    messagingSenderId: '227014811374',
    projectId: 'ititraining20232',
    storageBucket: 'ititraining20232.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCR-5aYu3dMvgSxbHDjZABFrFwmswig9M8',
    appId: '1:227014811374:ios:114e48b7be748f5a0cddff',
    messagingSenderId: '227014811374',
    projectId: 'ititraining20232',
    storageBucket: 'ititraining20232.appspot.com',
    iosClientId: '227014811374-ccdu9594e3e141prb736ucvhelu1tecg.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCR-5aYu3dMvgSxbHDjZABFrFwmswig9M8',
    appId: '1:227014811374:ios:1296b9ed47fdc52a0cddff',
    messagingSenderId: '227014811374',
    projectId: 'ititraining20232',
    storageBucket: 'ititraining20232.appspot.com',
    iosClientId: '227014811374-l0aadhqvsuuitln98nk9cod8jl71hspf.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled.RunnerTests',
  );
}
